<a href="https://colab.research.google.com/github/priyadharshini13/data_science/blob/master/PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#printing 7 random numbers
import numpy as np
data = {i: np.random.randn() for i in range(7)}
data

{0: 0.7713033293522523,
 1: -1.037535441439347,
 2: 1.6577514825583854,
 3: 0.12642822181779426,
 4: 1.363192800125643,
 5: -0.4111048087881821,
 6: 0.1643017661358485}

In [ ]:
data = {i: np.random.randint(10) for i in range(10)}
print(data)
data

{0: 7, 1: 8, 2: 4, 3: 0, 4: 2, 5: 9, 6: 6, 7: 3, 8: 9, 9: 9}


{0: 7, 1: 8, 2: 4, 3: 0, 4: 2, 5: 9, 6: 6, 7: 3, 8: 9, 9: 9}

In [ ]:
a = 10
b = 'success'
a?
b?

In [ ]:
data?

In [ ]:
def add_num(a,b):
  """
  Add two number
  """
  return a+b
add_num?

In [ ]:
add_num??

In [ ]:
np.*array*?

In [ ]:
#magic function
import numpy as np
#1. Timeit
a = np.random.randn(1,1)
%timeit np.dot(a,a)

The slowest run took 27.59 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 983 ns per loop


In [ ]:
#2. reset
a = 5
print(a)


5


In [ ]:
%reset -f
print(a)

NameError: ignored

In [ ]:
#3qucikref
%quickref

In [ ]:
# %magic
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl 

In [ ]:
%hist

#magic function
import numpy as np
#1. Timeit
a = np.random.randn(100,100)
%timeit np.dot(a,a)
#magic function
import numpy as np
#1. Timeit
a = np.random.randn(1,1)
%timeit np.dot(a,a)
#2. reset
a = 5
print(a)
%reset -f
print(a)
#2. reset
a = 5
print(a)
# %reset -f
# print(a)
%reset -f
print(a)
#3qucikref
%quickref
#3qucikref
%quickref
#3qucikref
%quickref
#3qucikref
%quickref
%magic
# %magic
%lsmagic
%debug a = b*4
%debug a = 4*4
%debug a = 4*4
%debug c a = 4*4
%debug a = 4*4, c
%hist


In [ ]:

# %page _
%who_ls

[]

In [ ]:
2 ** 3


8

In [ ]:
_

8

In [ ]:
__

8

In [ ]:
foo = 'bar'
foo

'bar'

In [ ]:
_i27

NameError: ignored

In [ ]:
_2

8

In [ ]:
_i?

In [ ]:
exec(_i1)

In [ ]:
%hist

2 ** 3
_
__
foo = 'bar'
foo
_i27
_i
_i27
_2
_i3
_i4
_i5
_i?
exec _i3
exec?
exec(_i1)
%hist


In [ ]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [ ]:
%history

2 ** 3
_
__
foo = 'bar'
foo
_i27
_i
_i27
_2
_i3
_i4
_i5
_i?
exec _i3
exec?
exec(_i1)
%hist
%reset
%hist
%history


In [ ]:
%logstart

Activating auto-logging. Current session state plus future input saved.
Filename       : ipython_log.py
Mode           : rotate
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


In [ ]:
%logstate

Filename       : ipython_log.py
Mode           : rotate
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


In [ ]:
!python

Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> ^C


In [ ]:
ip_info = !ifconfig eth0 | grep "inet"

In [ ]:
ip_info

['/bin/bash: ifconfig: command not found']

In [ ]:
run -d ch02/ipython_bug.py

ERROR:root:File `'ch02/ipython_bug.py'` not found.


In [ ]:
%run ipython_bug.py

ERROR:root:File `'ipython_bug.py'` not found.


In [ ]:
help()


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [ ]:
#Build-in time
import time
start = time.time()
for i in range(5):
  a = i+1
  i=i+1;
elapsed = (time.time() - start)/5
print(start)
print(elapsed)


1597334808.7382512
2.2172927856445312e-05


In [ ]:
#very large list of strings
strings = ['foo','foobar','baz','qux'] * 1000000
%time method1 = [x for x in strings if x.startswith('foo')]
%time method1 = [x for x in strings if x.startswith('foo')]

%time method2 = [x for x in strings if x[:3]=='foo']

CPU times: user 481 ms, sys: 15.9 ms, total: 497 ms
Wall time: 499 ms
CPU times: user 484 ms, sys: 0 ns, total: 484 ms
Wall time: 484 ms
CPU times: user 352 ms, sys: 1.93 ms, total: 354 ms
Wall time: 353 ms


In [ ]:
%timeit method1 = [x for x in strings if x.startswith('foo')]
%timeit method2 = [x for x in strings if x[:3]=='foo']

1 loop, best of 3: 467 ms per loop
1 loop, best of 3: 348 ms per loop


In [ ]:
%prun method1 = [x for x in strings if x.startswith('foo')]


In [ ]:
def add_and_sum(x,y):
  added = x + y
  summed = added.sum(axis=1)
  return summed

In [ ]:
from numpy.random import randn
def call_function():
  x = randn(3000,3000)
  y = randn(3000,3000)
  return add_and_sum(x,y)

In [ ]:

%prun call_function()

In [ ]:
%prun -f add_and_sum add_and_sum(x,y)

UsageError: option -f not recognized ( allowed: "D:l:rs:T:q" )


In [ ]:
import numpy as np
data = [1,2,3]
type(data)

list

In [ ]:
arr = np.array(data)
arr

array([1, 2, 3])

In [ ]:
data1 = [[1,23,4],[3,5,6]]
arr2 = np.array(data1)
arr2

array([[ 1, 23,  4],
       [ 3,  5,  6]])

In [ ]:
arr2.ndim?
y = np.zeros((2,3,4))
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr2.shape

(2, 3)

In [ ]:
y.shape
y.ndim

3

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,2,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
# loading gc 
import gc 
  
# get the current collection  
# thresholds as a tuple 
print("Garbage collection thresholds:", 
                    gc.get_threshold()) 

Garbage collection thresholds: (700, 10, 10)


In [ ]:
import gc 
i = 0 
  
# create a cycle and on each iteration x as a dictionary 
# assigned to 1 
def create_cycle(): 
    x = { } 
    x[i+1] = x 
    print(x) 
  
# lists are cleared whenever a full collection or  
# collection of the highest generation (2) is run 
collected = gc.collect() # or gc.collect(2) 
print("Garbage collector: collected {} objects".format(collected))
  
print("Creating cycles...")
for i in range(10): 
    create_cycle() 
  
collected = gc.collect() 
  
print("Garbage collector: collected {} objects.".format(collected))

Garbage collector: collected 41 objects
Creating cycles...
{1: {...}}
{2: {...}}
{3: {...}}
{4: {...}}
{5: {...}}
{6: {...}}
{7: {...}}
{8: {...}}
{9: {...}}
{10: {...}}
Garbage collector: collected 10 objects.


In [ ]:
np.empty((2,3,2))

array([[[2.40292503e-316, 2.10077583e-312],
        [2.29175545e-312, 2.31297541e-312],
        [2.01589600e-312, 2.46151512e-312]],

       [[2.10077583e-312, 8.48798317e-313],
        [2.48273508e-312, 8.70018275e-313],
        [8.70018275e-313, 1.46030983e-319]]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.ones_like(np.ones(10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])