<a href="https://colab.research.google.com/github/priyadharshini13/data_science/blob/master/Sherlock2nd_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sys
import tensorflow as tf
import matplotlib.pyplot as plt
from ast import literal_eval
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score
sys.path.append("..")

In [2]:
!unzip src

Archive:  src.zip
replace src/deploy/classes_retrain_minimal_sample.npy? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: src/deploy/classes_retrain_minimal_sample.npy  
  inflating: src/deploy/classes_sherlock.npy  
  inflating: src/deploy/predict_sherlock.py  
  inflating: src/deploy/train_sherlock.py  
  inflating: src/features/bag_of_characters.py  
  inflating: src/features/bag_of_words.py  
  inflating: src/features/build_features.py  
  inflating: src/features/feature_column_identifiers/char_col.tsv  
  inflating: src/features/feature_column_identifiers/par_col.tsv  
  inflating: src/features/feature_column_identifiers/rest_col.tsv  
  inflating: src/features/feature_column_identifiers/word_col.tsv  
  inflating: src/features/par_vec_trained_400.pkl  
  inflating: src/features/paragraph_vectors.py  
  inflating: src/features/word_embeddings.py  
  inflating: src/models/retrain_minimal_sample_model.json  
  inflating: src/models/sherlock_model.json  
  inflating: src/models/s

In [3]:
from src.features.build_features import build_features
from src.features.build_features import _get_data
from src.deploy.train_sherlock import train_sherlock
from src.deploy.predict_sherlock import predict_sherlock


In [62]:
from src.deploy.predict_sherlock import _prepare_sherlock_model
from src.deploy.predict_sherlock import _prepare_feature_cols
from src.deploy.predict_sherlock import _transform_predictions_to_classes

In [5]:
_get_data()

Data was downloaded.


In [6]:
X_test_preprocessed = pd.read_parquet('/data/data/processed/X_test.parquet')
y_test_preprocessed = pd.read_parquet('/data/data/processed/y_test.parquet').reset_index(drop=True)

In [7]:
X_test_preprocessed.head()


col_entropy  frac_unique  ...  par_vec_398  par_vec_399
0     2.122181        0.005  ...     0.054292    -0.049115
1     3.817487        0.015  ...    -0.069111    -0.112550
2     3.166061        0.009  ...    -0.041528    -0.094458
3     2.316887        0.005  ...     0.061907     0.065065
4     6.955528        0.163  ...    -0.139673    -0.115430

[5 rows x 1588 columns]

In [8]:
y_test_preprocessed.head()

label
0  affiliation
1       weight
2       jockey
3     religion
4      company

In [9]:
type(X_test_preprocessed)

pandas.core.frame.DataFrame

In [10]:
predicted_labels = predict_sherlock(X_test_preprocessed, 'sherlock')
print('Predicted labels: ', predicted_labels, 'true labels: ', y_test_preprocessed)

ValueError: ignored

In [11]:
sherlock = _prepare_sherlock_model('sherlock')
type(sherlock)
print(sherlock)

In [ ]:
tf.__version__

In [ ]:
sherlock.layers


In [ ]:
print(len(sherlock.layers))

In [ ]:
sherlock.name

In [ ]:
sherlock.trainable_weights

In [ ]:
sherlock.metrics

In [ ]:
# model = tf.keras.Sequential([
# tf.keras.layers.Dense(5, input_shape=(3,)),
# tf.keras.layers.Softmax()])
# config = model.to_json()
# loaded_model = tf.keras.models.model_from_json(config)
# config

In [13]:
feature_cols_dict = _prepare_feature_cols()
print(len(feature_cols_dict))
print(len(feature_cols_dict['char']))
print(len(feature_cols_dict['word']))
print(len(feature_cols_dict['par']))
print(len(feature_cols_dict['rest']))

4
960
201
400
27


In [21]:
sherlock.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 960)]        0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 201)]        0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            [(None, 400)]        0                                            
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 960)          3840        input_1[0][0]                    
______________________________________________________________________________________________

In [ ]:
with np.printoptions(threshold=np.inf):
    display(np.unique(X[feature_cols_dict['rest']].values))

In [44]:
with np.printoptions(threshold=np.inf):
    print(type(np.unique(X[feature_cols_dict['rest']].values)))

<class 'numpy.ndarray'>


In [46]:
len(X[feature_cols_dict['rest']].values)

137353

In [50]:
X[feature_cols_dict['rest']].values[0]
#137353 rows and 27 columns

array([2.1221809961106657, 0.005, 0.0, 1.0, 0.0, 0.0, 12.29,
       5.077194106984685, 0.0, 0.0, 1.7180000000000002,
       0.8857064976616125, 7, True, True, 13.008, 34.457936000000004, 4,
       23, 10.0, 13008, -0.9090802409651356, 0.24233320011559165, False,
       0.0, 0, False], dtype=object)

In [52]:
type(X[feature_cols_dict['rest']].values)


numpy.ndarray

In [54]:
arr = X[feature_cols_dict['rest']].values
a = arr.astype(float)
a[0]

array([ 2.12218100e+00,  5.00000000e-03,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.22900000e+01,  5.07719411e+00,
        0.00000000e+00,  0.00000000e+00,  1.71800000e+00,  8.85706498e-01,
        7.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.30080000e+01,
        3.44579360e+01,  4.00000000e+00,  2.30000000e+01,  1.00000000e+01,
        1.30080000e+04, -9.09080241e-01,  2.42333200e-01,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00])

In [56]:
a[0][1]

0.005

In [ ]:
X[feature_cols_dict['rest']].values
astype(float)

In [57]:
# ch = X[feature_cols_dict['char']].values
# ch = ch.astype(float)
y_pred = sherlock.predict([X[feature_cols_dict['char']].values.astype(float),
                               X[feature_cols_dict['word']].values.astype(float),
                               X[feature_cols_dict['par']].values.astype(float),
                               X[feature_cols_dict['rest']].values.astype(float)])
y_pred[0:5]

array([[7.15851955e-09, 1.00603738e-05, 9.99130905e-01, 2.89577824e-11,
        1.15475762e-08, 1.41885585e-06, 5.69408343e-08, 6.66702638e-10,
        1.47264236e-08, 6.74201956e-08, 4.75312678e-10, 1.01320765e-07,
        1.84419684e-11, 1.58631615e-08, 6.37802623e-06, 5.80178948e-06,
        5.58600805e-11, 3.10967927e-08, 8.27881941e-09, 3.19698813e-07,
        8.43444781e-08, 1.25888466e-09, 1.76223995e-08, 4.97836550e-10,
        1.73401240e-08, 2.74070857e-07, 1.39805652e-08, 1.00739095e-09,
        3.38800134e-11, 4.86834306e-09, 2.91461166e-08, 4.95226221e-11,
        8.77919604e-07, 1.25750160e-10, 7.07892722e-09, 7.23905935e-10,
        1.89355018e-10, 4.44984760e-09, 4.01780254e-09, 7.24534788e-09,
        1.50196911e-07, 4.16931795e-10, 2.68598654e-09, 2.36386573e-08,
        2.14308677e-08, 4.22628688e-07, 8.98918415e-08, 5.25205508e-07,
        2.61244537e-07, 1.23663835e-06, 3.37417805e-09, 2.05432916e-05,
        8.29435692e-07, 7.65557401e-04, 2.55943746e-07, 1.390511

In [ ]:
X = X_test_preprocessed
X.head()
np.nunique(X[feature_cols_dict['char']].values)

In [61]:
np.load('src/deploy/classes_sherlock.npy', allow_pickle=True)

array(['address', 'affiliate', 'affiliation', 'age', 'album', 'area',
       'artist', 'birth Date', 'birth Place', 'brand', 'capacity',
       'category', 'city', 'class', 'classification', 'club', 'code',
       'collection', 'command', 'company', 'component', 'continent',
       'country', 'county', 'creator', 'credit', 'currency', 'day',
       'depth', 'description', 'director', 'duration', 'education',
       'elevation', 'family', 'file Size', 'format', 'gender', 'genre',
       'grades', 'industry', 'isbn', 'jockey', 'language', 'location',
       'manufacturer', 'name', 'nationality', 'notes', 'operator',
       'order', 'organisation', 'origin', 'owner', 'person', 'plays',
       'position', 'product', 'publisher', 'range', 'rank', 'ranking',
       'region', 'religion', 'requirement', 'result', 'sales', 'service',
       'sex', 'species', 'state', 'status', 'symbol', 'team', 'team Name',
       'type', 'weight', 'year'], dtype=object)

In [65]:
output = _transform_predictions_to_classes(y_pred, 'sherlock')
output.shape
output

array(['affiliation', 'weight', 'jockey', ..., 'country', 'state', 'name'],
      dtype=object)

In [4]:
import pandas as pd
dd = pd.read_parquet('/data/data/raw/test_values.parquet')


values    ['Central Missouri', 'unattached', 'unattached...
Name: 20368, dtype: object

In [5]:
dd.iloc[0]

values    ['Central Missouri', 'unattached', 'unattached...
Name: 20368, dtype: object

In [9]:
val = dd.iloc[0]
val = dd.iloc[4]
val

values    ['AAF-McQuay Canada Inc.', 'AAF-McQuay Canada ...
Name: 176253, dtype: object

In [11]:
# proc = pd.read_parquet('/data/data/processed/X_val.parquet')
train = pd.read_parquet('/data/data/processed/X_train.parquet')
train.head()

col_entropy  frac_unique  ...  par_vec_398  par_vec_399
0     1.583978        0.003  ...     0.012795    -0.088069
1     0.709765        0.002  ...    -0.026614    -0.139599
2     2.683619        0.008  ...     0.009559    -0.049206
3     2.316898        0.005  ...    -0.026417    -0.149617
4     1.368901        0.004  ...    -0.032799    -0.320608

[5 rows x 1588 columns]